#!/usr/bin/env bash
# adds a custom HTTP header X-Served-By
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "35i\     add_header X-Served-By $HOSTNAME ;" /etc/nginx/sites-available/default
sudo service nginx restart
