#!/usr/bin/env bash
# adds a custom HTTP header X-Served-By
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37a\ $redirect" /etc/nginx/sites-enabled/default
page_404="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "37a\ $page_404" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
custom_header="\n\tadd_header X-Served-By 24276-web-02;"
sudo sed -i "37a\ $custom_header" /etc/nginx/sites-enabled/default
sudo service nginx restart
