#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt -y install haproxy
echo "
frontend node-http
    bind *:80
    mode http
    default_backend the_backend
backend the_backend
    balance roundrobin
    option forwardfor
    server 24276-web-01  18.208.132.167:80 check
    server 24276-web-02  18.232.119.117:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
service haproxy restart
